<?php

/**
 * BaseSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property integer $parent_id
 * @property enum $type
 * @property boolean $priority
 * @property string $image
 * @property Content $Content
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getName()      Returns the current record's "name" value
 * @method string  getSlug()      Returns the current record's "slug" value
 * @method integer getParentId()  Returns the current record's "parent_id" value
 * @method enum    getType()      Returns the current record's "type" value
 * @method boolean getPriority()  Returns the current record's "priority" value
 * @method string  getImage()     Returns the current record's "image" value
 * @method Content getContent()   Returns the current record's "Content" value
 * @method Section setId()        Sets the current record's "id" value
 * @method Section setName()      Sets the current record's "name" value
 * @method Section setSlug()      Sets the current record's "slug" value
 * @method Section setParentId()  Sets the current record's "parent_id" value
 * @method Section setType()      Sets the current record's "type" value
 * @method Section setPriority()  Sets the current record's "priority" value
 * @method Section setImage()     Sets the current record's "image" value
 * @method Section setContent()   Sets the current record's "Content" value
 * 
 * @package    Lavita
 * @subpackage model
 * @author     AlexanderDupree
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('section');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => false,
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'WithoutContent',
              1 => 'WithUniqueContent',
              2 => 'WithHTMLContent',
              3 => 'WithListContent',
             ),
             ));
        $this->hasColumn('priority', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Content', array(
             'local' => 'id',
             'foreign' => 'section_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}