<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CreatedContentTableWithColumns extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('content', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'html' => 
             array(
              'type' => 'clob',
              'notnull' => '',
              'length' => '',
             ),
             'section_id' => 
             array(
              'type' => 'integer',
              'unsigned' => '',
              'notnull' => '1',
              'length' => '4',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('content');
    }
}