<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddedVisibilityColumnToContent extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('content', 'visibility', 'boolean', '25', array(
             'default' => '0',
             ));
    }

    public function down()
    {
        $this->removeColumn('content', 'visibility');
    }
}