<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddedNewValueForTypeInSections extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('section', 'type', 'enum', '', array(
             'values' => 
             array(
              0 => 'WithoutContent',
              1 => 'WithUniqueContent',
              2 => 'WithHTMLContent',
              3 => 'WithListContent',
             ),
             ));
    }

    public function down()
    {

    }
}