<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddedImageColumnToSectionsTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('section', 'image', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('section', 'image');
    }
}