<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/03/21 16:30:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=lavita',
  'username' => 'root',
  'password' => '2011m@y24',
  'name' => 'doctrine',
)),);
