<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2015/04/11 18:28:03
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => '/Users/newapple/Sites/Lavita/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'basecontentformfilter' => '/Users/newapple/Sites/Lavita/lib/filter/doctrine/base/BaseContentFormFilter.class.php',
  'basesectionformfilter' => '/Users/newapple/Sites/Lavita/lib/filter/doctrine/base/BaseSectionFormFilter.class.php',
  'baseformfilterdoctrine' => '/Users/newapple/Sites/Lavita/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'contentformfilter' => '/Users/newapple/Sites/Lavita/lib/filter/doctrine/ContentFormFilter.class.php',
  'sectionformfilter' => '/Users/newapple/Sites/Lavita/lib/filter/doctrine/SectionFormFilter.class.php',
  'baseform' => '/Users/newapple/Sites/Lavita/lib/form/BaseForm.class.php',
  'basecontentform' => '/Users/newapple/Sites/Lavita/lib/form/doctrine/base/BaseContentForm.class.php',
  'basesectionform' => '/Users/newapple/Sites/Lavita/lib/form/doctrine/base/BaseSectionForm.class.php',
  'baseformdoctrine' => '/Users/newapple/Sites/Lavita/lib/form/doctrine/BaseFormDoctrine.class.php',
  'contentform' => '/Users/newapple/Sites/Lavita/lib/form/doctrine/ContentForm.class.php',
  'sectionform' => '/Users/newapple/Sites/Lavita/lib/form/doctrine/SectionForm.class.php',
  'addedcontenttable' => '/Users/newapple/Sites/Lavita/lib/migration/doctrine/001_AddedContentTable.php',
  'createdcontenttablewithcolumns' => '/Users/newapple/Sites/Lavita/lib/migration/doctrine/002_CreatedContentTableWithColumns.php',
  'generatedrelationsforcontenttable' => '/Users/newapple/Sites/Lavita/lib/migration/doctrine/003_GeneratedRelationsForContentTable.php',
  'addedvisibilitycolumntocontent' => '/Users/newapple/Sites/Lavita/lib/migration/doctrine/004_AddedVisibilityColumnToContent.php',
  'addednewvaluefortypeinsections' => '/Users/newapple/Sites/Lavita/lib/migration/doctrine/005_AddedNewValueForTypeInSections.php',
  'addedimagecolumntosectionstable' => '/Users/newapple/Sites/Lavita/lib/migration/doctrine/006_AddedImageColumnToSectionsTable.php',

  // project_model
  'basecontent' => '/Users/newapple/Sites/Lavita/lib/model/doctrine/base/BaseContent.class.php',
  'basesection' => '/Users/newapple/Sites/Lavita/lib/model/doctrine/base/BaseSection.class.php',
  'content' => '/Users/newapple/Sites/Lavita/lib/model/doctrine/Content.class.php',
  'contenttable' => '/Users/newapple/Sites/Lavita/lib/model/doctrine/ContentTable.class.php',
  'section' => '/Users/newapple/Sites/Lavita/lib/model/doctrine/Section.class.php',
  'sectiontable' => '/Users/newapple/Sites/Lavita/lib/model/doctrine/SectionTable.class.php',

  // application
  'myuser' => '/Users/newapple/Sites/Lavita/apps/admin/lib/myUser.class.php',

  // modules
);
